import Image from "next/image";
import Link from "next/link";

import { APP_NAME } from "@/lib/constants";
import { cn } from "@/lib/utils";

/** Full logo dimensions — generated by `node scripts/generate-logo.mjs`. */
const LOGO_WIDTH = 126;
const LOGO_HEIGHT = 36;
const MARK_SIZE = 36;

export function Logo({
  className,
  href = "/",
  variant = "full",
  inverted = false,
}: {
  className?: string;
  href?: string;
  variant?: "full" | "mark";
  inverted?: boolean;
}) {
  const isMarkOnly = variant === "mark";
  const src = isMarkOnly
    ? "/logo-mark.png"
    : inverted
      ? "/logo-inverted.png"
      : "/logo.png";

  return (
    <Link
      href={href}
      className={cn("inline-flex items-center", className)}
      aria-label={APP_NAME}
    >
      <Image
        src={src}
        alt={APP_NAME}
        width={isMarkOnly ? MARK_SIZE : LOGO_WIDTH}
        height={LOGO_HEIGHT}
        priority
        className="h-9 w-auto object-contain object-left"
      />
    </Link>
  );
}
