"use client";

import Image from "next/image";
import Link from "next/link";

import { APP_NAME } from "@/lib/constants";
import { cn } from "@/lib/utils";

/** Full logo dimensions — generated by `node scripts/generate-logo.mjs`. */
const LOGO_WIDTH = 206;
const LOGO_HEIGHT = 36;
const MARK_SIZE = 36;

const imageClass = "h-9 w-auto object-contain object-left";

export function Logo({
  className,
  href = "/",
  variant = "full",
  inverted = false,
}: {
  className?: string;
  href?: string;
  variant?: "full" | "mark";
  inverted?: boolean;
}) {
  const isMarkOnly = variant === "mark";

  return (
    <Link
      href={href}
      className={cn("inline-flex items-center", className)}
      aria-label={APP_NAME}
    >
      {isMarkOnly ? (
        <Image
          src="/logo-mark.png"
          alt={APP_NAME}
          width={MARK_SIZE}
          height={LOGO_HEIGHT}
          priority
          className={imageClass}
        />
      ) : inverted ? (
        <Image
          src="/logo-inverted.png"
          alt={APP_NAME}
          width={LOGO_WIDTH}
          height={LOGO_HEIGHT}
          priority
          className={imageClass}
        />
      ) : (
        <>
          <Image
            src="/logo.png"
            alt={APP_NAME}
            width={LOGO_WIDTH}
            height={LOGO_HEIGHT}
            priority
            className={cn(imageClass, "dark:hidden")}
          />
          <Image
            src="/logo-inverted.png"
            alt={APP_NAME}
            width={LOGO_WIDTH}
            height={LOGO_HEIGHT}
            priority
            className={cn(imageClass, "hidden dark:block")}
          />
        </>
      )}
    </Link>
  );
}
